dbdsn="file:./vol/db.sqlite"
admin_user = ["admin","netroby"]
site_name = "leobbs"
site_description = "My memory about leobbs"
key_of_encrypt = "leobbs1314"
[object_storage]
aws_access_key_id = "*****"
aws_secret_access_key = "******"
aws_region = "us-east-1"
aws_bucket = "www.domain.com"
cdn_url = "//www.domain.com"
[email]
smtp_host = "smtp.example.com"
smtp_port = "25"
username = "master@domain.com"
password = "securitypassword"
[tongji_config]
tongji_enabled=1
tongji_code='''
<script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?73258af02049f461ac06ca5f9d9b1f55";
            hm.async = true;
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
'''